# Generated by Django 3.2.4 on 2021-08-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTaxonomy',
            fields=[
                ('taxonomy_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('field_class', models.CharField(max_length=250, null=True)),
                ('medicare_description', models.CharField(max_length=250, null=True)),
                ('specialization', models.CharField(max_length=250, null=True)),
                ('area_of_expertise', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSpecTaxonomy',
            fields=[
                ('taxonomy_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('field_class', models.CharField(max_length=250, null=True)),
                ('medicare_description', models.CharField(max_length=250, null=True)),
                ('specialization', models.CharField(max_length=250, null=True)),
                ('area_of_expertise', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTypeTaxonomy',
            fields=[
                ('taxonomy_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
