# Generated by Django 3.2.4 on 2021-09-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymous_comment_and_whistelblow',
            old_name='rating',
            new_name='rating_obj',
        ),
        migrations.RenameField(
            model_name='characterconductratings',
            old_name='rating',
            new_name='rating_obj',
        ),
        migrations.RenameField(
            model_name='patientcare',
            old_name='rating',
            new_name='rating_obj',
        ),
        migrations.RenameField(
            model_name='professionalskill',
            old_name='rating',
            new_name='rating_obj',
        ),
    ]
