# Generated by Django 3.2.4 on 2021-08-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='character_and_conduct',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='patient_centered_care',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='professional_skill',
        ),
        migrations.CreateModel(
            name='ProfSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ratings.rating')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_centered_care', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ratings.rating')),
            ],
        ),
        migrations.CreateModel(
            name='CharConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_and_conduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ratings.rating')),
            ],
        ),
    ]
