# Generated by Django 3.2.4 on 2021-09-17 19:34

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Taxonomy', '0001_initial'),
        ('Hospitals', '0001_initial'),
        ('NPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('doctor_npi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NPI.doctornpi')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('credential_text', models.CharField(blank=True, max_length=5, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=250)),
                ('license_state', localflavor.us.models.USStateField(max_length=2)),
                ('sole_proprietor', models.BooleanField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=10)),
                ('years_in_current_hospital', models.IntegerField(null=True)),
                ('experience', models.IntegerField()),
                ('image_url', models.CharField(default='Doctors\\static\\Pages\\images\\medical-doctor-profile-icon-male-portrait-flat-design-EY25CP.jpg', max_length=200)),
                ('doctor_taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctaxonomy', to='Taxonomy.doctortaxonomy')),
                ('hospital_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitals.hospitalsystem')),
            ],
        ),
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Doctors.doctor')),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(default='Tulsa', max_length=64)),
                ('state', localflavor.us.models.USStateField(default='OK', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default='74119', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAddress',
            fields=[
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Doctors.doctor')),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(default='Tulsa', max_length=64)),
                ('state', localflavor.us.models.USStateField(default='OK', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default='74119', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='mailing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctormailing', to='Doctors.mailingaddress'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctorpractice', to='Doctors.practiceaddress'),
        ),
    ]
